apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-base-application
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istio/base
    targetRevision: 1.16.1
    helm:
      values: |
        defaultRevision: "1-16-1"

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
