apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-gateway-application
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.15.4
    helm:
      values: |
        service:
          type: NodePort
          ports:
            - name: http
          port: 80
          targetPort: 8080
          nodePort: 31039
          affinity:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node.kubernetes.io/nodegroup
                      operator: In
                      values:
                        - ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
