apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: jaeger-application
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 0.66.1
    helm:
      releaseName: jaeger
      values: |
        agent:
          enabled: false
        collector:
          service:
            zipkin:
              port: 9411
          nodeSelector:
            node.kubernetes.io/nodegroup: system
        query:
          ingress:
            enabled: true
            ingressClassName: nginx
          nodeSelector:
            node.kubernetes.io/nodegroup: system
        cassandra:
          {{- /* EmptyDirではなく、PersistentVolumeを使用する */}}
          persistence:
           enabled: true
        schema:
          {{- /* Cassandraに環境変数を設定する */}}
          {{- /* https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/cassandra/schema/create.sh */}}
          extraEnv:
            - name: "MODE"
              value: "prod"
            - name: "TRACE_TTL"
              value: "300"

  destination:
    server: https://kubernetes.default.svc
    namespace: jaeger
