apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: infra-shared-application
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  project: infra
  source:
    repoURL: https://github.com/hiroki-it/helm-charts-practice.git
    targetRevision: main
    path: ./infra/shared
    helm:
      valueFiles:
        - ./values-{{ .Values.global.env }}.yaml
  destination:
    server: https://kubernetes.default.svc
