apiVersion: v1
kind: Namespace
metadata:
  name: fluentbit
---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    # istio-proxyコンテナのインジェクションを有効化する。
    istio.io/rev: stable
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
