apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: app
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: paulbouwer/hello-kubernetes:1.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/nodegroup
                    operator: In
                    values:
                      - app
