apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
  namespace: app
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http-helloworld
        number: 80
        protocol: 80
      hosts:
        - helloworld-service.app.svc.cluster.local
