apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.global.serviceName }}-gateway
  namespace: app
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http-{{ .Values.global.serviceName }}
        number: {{ .Values.ingressGateway.port }}
        protocol: HTTP
      hosts:
        - {{ .Values.global.serviceName }}-service.app.svc.cluster.local
