apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: app
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
