repositories:
  - name: argo-helm
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    chart: argo-helm/argo-cd
    version: 5.16.3
    atomic: true
    values:
      - ../charts/argocd/values.yaml.gotmpl
      - ../charts/argocd/values-{{ .Environment.Name }}.yaml

environments:
  prd:
  dev:
