apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld-virtual-service
  namespace: app
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  hosts:
    - "*"
  gateways:
    - helloworld-gateway
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: helloworld-service. helloworld.svc.cluster.local
            port:
              number: 8080

