extraObjects:
  # Minikubeを使用するdev環境では、追加でNodePort Serviceも作成する。
  - apiVersion: v1
    kind: Service
    metadata:
      name: extra-argocd-server
      namespace: argocd
    spec:
      type: NodePort
      ports:
        - name: http
          protocol: TCP
          nodePort: 30080
          port: 80
        - name: https
          protocol: TCP
          nodePort: 30443
          port: 443
      selector:
        app.kubernetes.io/name: argocd-server
