apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app
  labels:
    app.kubernetes.io/env: {{ .Values.global.env }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
